// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cyu.laclad.domain;

import com.cyu.laclad.domain.Phone;

privileged aspect Phone_Roo_JavaBean {
    
    public Long Phone.getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void Phone.setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
}
