// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cyu.laclad.domain;

import com.cyu.laclad.domain.Representant;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Representant_Roo_Configurable {
    
    declare @type: Representant: @Configurable;
    
}
